### ISSUE TITLE
Uncaught ReferenceError: require is not defined at index.html:17

### ISSUE THREAD

**Issue by Dzhuneyt** [achekulaev/minimal-electron-react-app#1]
After checkout and installation steps, I get this after an "npm start":

![image](https://user-images.githubusercontent.com/1754428/64526791-e5347780-d30c-11e9-9e0c-20bce241505a.png)
![image](https://user-images.githubusercontent.com/1754428/64526798-ebc2ef00-d30c-11e9-9397-af98e5cf5501.png)

Using Ubuntu 18.04 LTS and Chrome 76.0.3809.132 (Official Build) (64-bit). Ideas?

**Comment by nekapoor** [comment]
@Dzhuneyt did you ever get a resolution for this issue? I'm running into the same thing. Thanks

**Comment by Dzhuneyt** [comment]
Not really. I was hoping @achekulaev has some ideas.

**Comment by achekulaev** [comment]
With 3 stars for the project I did not expect suprising number of people using it. I'll take a look

**Comment by achekulaev** [comment]
There you go guys @Dzhuneyt @nekapoor 
Thanks for bringing this up

**Comment by Dzhuneyt** [comment]
Thanks, @achekulaev. You just got one more star from me. :)
